### ISSUE TITLE
AttributeError: 'NoneType' object

### ISSUE THREAD

**Issue by scottleibrand** [bewest/openxshareble#1]
```
pi@rpi3 ~/openaps-dev $ openaps use share glucose
INIT WITH SERIAL SM51118275
[ /org/bluez/hci0 ]
    org.bluez.ThermometerManager1
    org.bluez.CyclingSpeedManager1
    org.bluez.Media1
    org.bluez.HeartRateManager1
    org.bluez.NetworkServer1
    org.bluez.Adapter1
      Name = rpi3
      Powered = 1
      Modalias = usb:v1D6Bp0246d0517
      DiscoverableTimeout = 180
      Alias = rpi3
      PairableTimeout = 0
      Discoverable = 0
      Address = 5C:F3:70:6B:3D:6B
      Discovering = 0
      Pairable = 1
      Class = 0
      UUIDs = dbus.Array([dbus.String(u'00001200-0000-1000-8000-00805f9b34fb'), dbus.String(u'00001800-0000-1000-8000-00805f9b34fb'), dbus.String(u'00001801-0000-1000-8000-00805f9b34fb'), dbus.String(u'0000110e-0000-1000-8000-00805f9b34fb'), dbus.String(u'0000110c-0000-1000-8000-00805f9b34fb')], signature=dbus.Signature('s'), variant_level=1)
[ /org/bluez ]
    org.bluez.ProfileManager1
    org.bluez.HealthManager1
    org.bluez.Alert1
    org.bluez.AgentManager1
[ /org/bluez/hci0/dev_FF_F3_8F_02_29_46 ]
    org.bluez.Device1
      Name = DEXCOMRX
      Paired = 0
      Adapter = /org/bluez/hci0
      LegacyPairing = 0
      Alias = DEXCOMRX
      Connected = 1
      UUIDs = dbus.Array([dbus.String(u'f0aca0b1-ebfa-f96f-28da-076c35a521db')], signature=dbus.Signature('s'), variant_level=1)
      Address = FF:F3:8F:02:29:46
      Trusted = 0
      Blocked = 0
None
paired? 0
pairing...
paired
[UUID('00001800-0000-1000-8000-00805f9b34fb'), UUID('00001801-0000-1000-8000-00805f9b34fb'), UUID('00001804-0000-1000-8000-00805f9b34fb'), UUID('0000180a-0000-1000-8000-00805f9b34fb'), UUID('f0aca0b1-ebfa-f96f-28da-076c35a521db')]
finding service
SERVICE None
Traceback (most recent call last):
  File "/usr/local/bin/openaps-use", line 4, in <module>
    __import__('pkg_resources').run_script('openaps==0.0.9', 'openaps-use')
  File "build/bdist.linux-armv7l/egg/pkg_resources/__init__.py", line 742, in run_script
  File "build/bdist.linux-armv7l/egg/pkg_resources/__init__.py", line 1667, in run_script
  File "/usr/local/lib/python2.7/dist-packages/openaps-0.0.9-py2.7.egg/EGG-INFO/scripts/openaps-use", line 63, in <module>
    app( )
  File "/usr/local/lib/python2.7/dist-packages/openaps-0.0.9-py2.7.egg/openaps/cli/__init__.py", line 44, in __call__
    self.run(self.args)
  File "/usr/local/lib/python2.7/dist-packages/openaps-0.0.9-py2.7.egg/EGG-INFO/scripts/openaps-use", line 57, in run
    output = app(args, self)
  File "/usr/local/lib/python2.7/dist-packages/openaps-0.0.9-py2.7.egg/openaps/uses/__init__.py", line 92, in __call__
    return self.method.selected(args)(args, app)
  File "/usr/local/lib/python2.7/dist-packages/openaps-0.0.9-py2.7.egg/openaps/uses/__init__.py", line 31, in __call__
    return self.method(args, app)
  File "/home/pi/src/openxshareble/openxshareble/__init__.py", line 58, in __call__
    res = self.ble.run_mainloop_with(run, quit_with_loop=False)
  File "/home/pi/src/Adafruit_Python_BluefruitLE/Adafruit_BluefruitLE/bluez_dbus/provider.py", line 121, in _user_thread_main
    self._return_code = target()
  File "/home/pi/src/openxshareble/openxshareble/__init__.py", line 55, in run
    output = self.main(args, app)
  File "/usr/local/lib/python2.7/dist-packages/openaps-0.0.9-py2.7.egg/openaps/vendors/dexcom.py", line 67, in main
    records = self.dexcom.ReadRecords('EGV_DATA')
AttributeError: 'NoneType' object has no attribute 'ReadRecords'
pi@rpi3 ~/openaps-dev $
```

```
pi@rpi3 ~/openaps-dev $ openaps use share list_dexcom
INIT WITH SERIAL SM51118275
[ /org/bluez/hci0 ]
    org.bluez.ThermometerManager1
    org.bluez.CyclingSpeedManager1
    org.bluez.Media1
    org.bluez.HeartRateManager1
    org.bluez.NetworkServer1
    org.bluez.Adapter1
      Name = rpi3
      Powered = 1
      Modalias = usb:v1D6Bp0246d0517
      DiscoverableTimeout = 180
      Alias = rpi3
      PairableTimeout = 0
      Discoverable = 0
      Address = 5C:F3:70:6B:3D:6B
      Discovering = 0
      Pairable = 1
      Class = 0
      UUIDs = dbus.Array([dbus.String(u'00001200-0000-1000-8000-00805f9b34fb'), dbus.String(u'00001800-0000-1000-8000-00805f9b34fb'), dbus.String(u'00001801-0000-100
0-8000-00805f9b34fb'), dbus.String(u'0000110e-0000-1000-8000-00805f9b34fb'), dbus.String(u'0000110c-0000-1000-8000-00805f9b34fb')], signature=dbus.Signature('s'), va
riant_level=1)
[ /org/bluez ]
    org.bluez.ProfileManager1
    org.bluez.HealthManager1
    org.bluez.Alert1
    org.bluez.AgentManager1
[ /org/bluez/hci0/dev_FF_F3_8F_02_29_46 ]
    org.bluez.Device1
      Name = DEXCOMRX
      Paired = 0
      Adapter = /org/bluez/hci0
      LegacyPairing = 0
      Alias = DEXCOMRX
      Connected = 1
      UUIDs = dbus.Array([dbus.String(u'f0aca0b1-ebfa-f96f-28da-076c35a521db')], signature=dbus.Signature('s'), variant_level=1)
      Address = FF:F3:8F:02:29:46
      Trusted = 0
      Blocked = 0
None
paired? 0
pairing...
paired
[UUID('00001800-0000-1000-8000-00805f9b34fb'), UUID('00001801-0000-1000-8000-00805f9b34fb'), UUID('00001804-0000-1000-8000-00805f9b34fb'), UUID('0000180a-0000-1000-8
000-00805f9b34fb'), UUID('f0aca0b1-ebfa-f96f-28da-076c35a521db')]
finding service
SERVICE None
Searching for UART devices...
[
  {
    "mac": "FF:F3:8F:02:29:46",
    "name": "DEXCOMRX",
    "advertised": [
      "00001800-0000-1000-8000-00805f9b34fb",
      "00001801-0000-1000-8000-00805f9b34fb",
      "00001804-0000-1000-8000-00805f9b34fb",
      "0000180a-0000-1000-8000-00805f9b34fb",
      "f0aca0b1-ebfa-f96f-28da-076c35a521db"
    ]
  }
]pi@rpi3 ~/openaps-dev $
```

**Comment by scottleibrand** [comment]
Verified that it does this with only one Dexcom Share in range.
